/* tslint:disable */
/* eslint-disable */
/**
 * Новосибирск BMW Клуб API
 * API спецификация api.bmw-nsk.ru
 *
 * The version of the OpenAPI document: 1.0
 * Contact: evist0@dblade.tech
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { BuildingEntity } from './building-entity';
// May contain unused imports in some cases
// @ts-ignore
import { BuildingsControllerFind200ResponseAllOf } from './buildings-controller-find200-response-all-of';
// May contain unused imports in some cases
// @ts-ignore
import { PaginatedEntity } from './paginated-entity';

/**
 * @type BuildingsControllerFind200Response
 * @export
 */
export type BuildingsControllerFind200Response = BuildingsControllerFind200ResponseAllOf & PaginatedEntity;


