/* tslint:disable */
/* eslint-disable */
/**
 * Пожликбез APIирск BMW Клуб API
 * API спецификация api.bmw-nsk.ru
 *
 * The version of the OpenAPI document: 1.0
 * Contact: kurskatm@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface BuildingEntityCoordinate
 */
export interface BuildingEntityCoordinate {
    /**
     * 
     * @type {number}
     * @memberof BuildingEntityCoordinate
     */
    'lat': number;
    /**
     * 
     * @type {number}
     * @memberof BuildingEntityCoordinate
     */
    'lon': number;
}

