/* tslint:disable */
/* eslint-disable */
/**
 * Новосибирск BMW Клуб API
 * API спецификация api.bmw-nsk.ru
 *
 * The version of the OpenAPI document: 1.0
 * Contact: evist0@dblade.tech
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface BuildingCategoriesSortingDto
 */
export interface BuildingCategoriesSortingDto {
    /**
     * 
     * @type {string}
     * @memberof BuildingCategoriesSortingDto
     */
    'id'?: BuildingCategoriesSortingDtoIdEnum;
    /**
     * 
     * @type {string}
     * @memberof BuildingCategoriesSortingDto
     */
    'name'?: BuildingCategoriesSortingDtoNameEnum;
    /**
     * 
     * @type {string}
     * @memberof BuildingCategoriesSortingDto
     */
    'lowerName'?: BuildingCategoriesSortingDtoLowerNameEnum;
    /**
     * 
     * @type {string}
     * @memberof BuildingCategoriesSortingDto
     */
    'createdAt'?: BuildingCategoriesSortingDtoCreatedAtEnum;
    /**
     * 
     * @type {string}
     * @memberof BuildingCategoriesSortingDto
     */
    'updatedAt'?: BuildingCategoriesSortingDtoUpdatedAtEnum;
}

export const BuildingCategoriesSortingDtoIdEnum = {
    Asc: 'asc',
    Desc: 'desc'
} as const;

export type BuildingCategoriesSortingDtoIdEnum = typeof BuildingCategoriesSortingDtoIdEnum[keyof typeof BuildingCategoriesSortingDtoIdEnum];
export const BuildingCategoriesSortingDtoNameEnum = {
    Asc: 'asc',
    Desc: 'desc'
} as const;

export type BuildingCategoriesSortingDtoNameEnum = typeof BuildingCategoriesSortingDtoNameEnum[keyof typeof BuildingCategoriesSortingDtoNameEnum];
export const BuildingCategoriesSortingDtoLowerNameEnum = {
    Asc: 'asc',
    Desc: 'desc'
} as const;

export type BuildingCategoriesSortingDtoLowerNameEnum = typeof BuildingCategoriesSortingDtoLowerNameEnum[keyof typeof BuildingCategoriesSortingDtoLowerNameEnum];
export const BuildingCategoriesSortingDtoCreatedAtEnum = {
    Asc: 'asc',
    Desc: 'desc'
} as const;

export type BuildingCategoriesSortingDtoCreatedAtEnum = typeof BuildingCategoriesSortingDtoCreatedAtEnum[keyof typeof BuildingCategoriesSortingDtoCreatedAtEnum];
export const BuildingCategoriesSortingDtoUpdatedAtEnum = {
    Asc: 'asc',
    Desc: 'desc'
} as const;

export type BuildingCategoriesSortingDtoUpdatedAtEnum = typeof BuildingCategoriesSortingDtoUpdatedAtEnum[keyof typeof BuildingCategoriesSortingDtoUpdatedAtEnum];


