/* tslint:disable */
/* eslint-disable */
/**
 * Новосибирск BMW Клуб API
 * API спецификация api.bmw-nsk.ru
 *
 * The version of the OpenAPI document: 1.0
 * Contact: evist0@dblade.tech
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { BuildingCategoryEntity } from './building-category-entity';

/**
 * 
 * @export
 * @interface BuildingCategoriesControllerFind200ResponseAllOf
 */
export interface BuildingCategoriesControllerFind200ResponseAllOf {
    /**
     * 
     * @type {Array<BuildingCategoryEntity>}
     * @memberof BuildingCategoriesControllerFind200ResponseAllOf
     */
    'data'?: Array<BuildingCategoryEntity>;
}

