/* tslint:disable */
/* eslint-disable */
/**
 * Пожликбез APIирск BMW Клуб API
 * API спецификация api.bmw-nsk.ru
 *
 * The version of the OpenAPI document: 1.0
 * Contact: kurskatm@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Заведение не найдено.
 * @export
 * @interface BuildingsControllerFindOne404Response
 */
export interface BuildingsControllerFindOne404Response {
    /**
     * 
     * @type {number}
     * @memberof BuildingsControllerFindOne404Response
     */
    'statusCode': number;
    /**
     * 
     * @type {string}
     * @memberof BuildingsControllerFindOne404Response
     */
    'message': string;
    /**
     * 
     * @type {string}
     * @memberof BuildingsControllerFindOne404Response
     */
    'error'?: string;
}

