/* tslint:disable */
/* eslint-disable */
/**
 * Новосибирск BMW Клуб API
 * API спецификация api.bmw-nsk.ru
 *
 * The version of the OpenAPI document: 1.0
 * Contact: evist0@dblade.tech
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { BuildingEntityCoordinate } from './building-entity-coordinate';

/**
 * 
 * @export
 * @interface BuildingEntity
 */
export interface BuildingEntity {
    /**
     * 
     * @type {number}
     * @memberof BuildingEntity
     */
    'id': number;
    /**
     * 
     * @type {string}
     * @memberof BuildingEntity
     */
    'partnerId': string;
    /**
     * 
     * @type {string}
     * @memberof BuildingEntity
     */
    'phone': string | null;
    /**
     * 
     * @type {string}
     * @memberof BuildingEntity
     */
    'district': string | null;
    /**
     * 
     * @type {string}
     * @memberof BuildingEntity
     */
    'street': string | null;
    /**
     * 
     * @type {string}
     * @memberof BuildingEntity
     */
    'housenumber': string;
    /**
     * 
     * @type {BuildingEntityCoordinate}
     * @memberof BuildingEntity
     */
    'coordinate': BuildingEntityCoordinate;
    /**
     * 
     * @type {string}
     * @memberof BuildingEntity
     */
    'createdAt': string;
    /**
     * 
     * @type {string}
     * @memberof BuildingEntity
     */
    'updatedAt': string;
}

