/* tslint:disable */
/* eslint-disable */
/**
 * Новосибирск BMW Клуб API
 * API спецификация api.bmw-nsk.ru
 *
 * The version of the OpenAPI document: 1.0
 * Contact: evist0@dblade.tech
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { BuildingEntityCategoriesInner } from './building-entity-categories-inner';
// May contain unused imports in some cases
// @ts-ignore
import { BuildingEntityOffersInner } from './building-entity-offers-inner';

/**
 * 
 * @export
 * @interface BuildingEntity
 */
export interface BuildingEntity {
    /**
     * 
     * @type {string}
     * @memberof BuildingEntity
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof BuildingEntity
     */
    'partnerId': string;
    /**
     * 
     * @type {string}
     * @memberof BuildingEntity
     */
    'phone': string | null;
    /**
     * 
     * @type {string}
     * @memberof BuildingEntity
     */
    'city': string;
    /**
     * 
     * @type {string}
     * @memberof BuildingEntity
     */
    'district': string | null;
    /**
     * 
     * @type {string}
     * @memberof BuildingEntity
     */
    'street': string;
    /**
     * 
     * @type {string}
     * @memberof BuildingEntity
     */
    'houseNumber': string;
    /**
     * 
     * @type {number}
     * @memberof BuildingEntity
     */
    'lat': number;
    /**
     * 
     * @type {number}
     * @memberof BuildingEntity
     */
    'lon': number;
    /**
     * 
     * @type {Array<BuildingEntityCategoriesInner>}
     * @memberof BuildingEntity
     */
    'categories': Array<BuildingEntityCategoriesInner>;
    /**
     * 
     * @type {Array<BuildingEntityOffersInner>}
     * @memberof BuildingEntity
     */
    'offers': Array<BuildingEntityOffersInner>;
    /**
     * 
     * @type {string}
     * @memberof BuildingEntity
     */
    'createdAt': string;
    /**
     * 
     * @type {string}
     * @memberof BuildingEntity
     */
    'updatedAt': string;
}

