/* tslint:disable */
/* eslint-disable */
/**
 * Новосибирск BMW Клуб API
 * API спецификация api.bmw-nsk.ru
 *
 * The version of the OpenAPI document: 1.0
 * Contact: evist0@dblade.tech
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { BuildingEntity } from './building-entity';
// May contain unused imports in some cases
// @ts-ignore
import { BuildingsControllerFindAll200ResponseAllOf } from './buildings-controller-find-all200-response-all-of';
// May contain unused imports in some cases
// @ts-ignore
import { PaginationResultDto } from './pagination-result-dto';

/**
 * @type BuildingsControllerFindAll200Response
 * @export
 */
export type BuildingsControllerFindAll200Response = BuildingsControllerFindAll200ResponseAllOf & PaginationResultDto;


