/* tslint:disable */
/* eslint-disable */
/**
 * Новосибирск BMW Клуб API
 * API спецификация api.bmw-nsk.ru
 *
 * The version of the OpenAPI document: 1.0
 * Contact: evist0@dblade.tech
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface BuildingsSortingDto
 */
export interface BuildingsSortingDto {
    /**
     * 
     * @type {string}
     * @memberof BuildingsSortingDto
     */
    'id'?: BuildingsSortingDtoIdEnum;
    /**
     * 
     * @type {string}
     * @memberof BuildingsSortingDto
     */
    'partnerId'?: BuildingsSortingDtoPartnerIdEnum;
    /**
     * 
     * @type {string}
     * @memberof BuildingsSortingDto
     */
    'phone'?: BuildingsSortingDtoPhoneEnum;
    /**
     * 
     * @type {string}
     * @memberof BuildingsSortingDto
     */
    'city'?: BuildingsSortingDtoCityEnum;
    /**
     * 
     * @type {string}
     * @memberof BuildingsSortingDto
     */
    'district'?: BuildingsSortingDtoDistrictEnum;
    /**
     * 
     * @type {string}
     * @memberof BuildingsSortingDto
     */
    'street'?: BuildingsSortingDtoStreetEnum;
    /**
     * 
     * @type {string}
     * @memberof BuildingsSortingDto
     */
    'houseNumber'?: BuildingsSortingDtoHouseNumberEnum;
    /**
     * 
     * @type {string}
     * @memberof BuildingsSortingDto
     */
    'lat'?: BuildingsSortingDtoLatEnum;
    /**
     * 
     * @type {string}
     * @memberof BuildingsSortingDto
     */
    'lon'?: BuildingsSortingDtoLonEnum;
    /**
     * 
     * @type {string}
     * @memberof BuildingsSortingDto
     */
    'createdAt'?: BuildingsSortingDtoCreatedAtEnum;
    /**
     * 
     * @type {string}
     * @memberof BuildingsSortingDto
     */
    'updatedAt'?: BuildingsSortingDtoUpdatedAtEnum;
}

export const BuildingsSortingDtoIdEnum = {
    Asc: 'asc',
    Desc: 'desc'
} as const;

export type BuildingsSortingDtoIdEnum = typeof BuildingsSortingDtoIdEnum[keyof typeof BuildingsSortingDtoIdEnum];
export const BuildingsSortingDtoPartnerIdEnum = {
    Asc: 'asc',
    Desc: 'desc'
} as const;

export type BuildingsSortingDtoPartnerIdEnum = typeof BuildingsSortingDtoPartnerIdEnum[keyof typeof BuildingsSortingDtoPartnerIdEnum];
export const BuildingsSortingDtoPhoneEnum = {
    Asc: 'asc',
    Desc: 'desc'
} as const;

export type BuildingsSortingDtoPhoneEnum = typeof BuildingsSortingDtoPhoneEnum[keyof typeof BuildingsSortingDtoPhoneEnum];
export const BuildingsSortingDtoCityEnum = {
    Asc: 'asc',
    Desc: 'desc'
} as const;

export type BuildingsSortingDtoCityEnum = typeof BuildingsSortingDtoCityEnum[keyof typeof BuildingsSortingDtoCityEnum];
export const BuildingsSortingDtoDistrictEnum = {
    Asc: 'asc',
    Desc: 'desc'
} as const;

export type BuildingsSortingDtoDistrictEnum = typeof BuildingsSortingDtoDistrictEnum[keyof typeof BuildingsSortingDtoDistrictEnum];
export const BuildingsSortingDtoStreetEnum = {
    Asc: 'asc',
    Desc: 'desc'
} as const;

export type BuildingsSortingDtoStreetEnum = typeof BuildingsSortingDtoStreetEnum[keyof typeof BuildingsSortingDtoStreetEnum];
export const BuildingsSortingDtoHouseNumberEnum = {
    Asc: 'asc',
    Desc: 'desc'
} as const;

export type BuildingsSortingDtoHouseNumberEnum = typeof BuildingsSortingDtoHouseNumberEnum[keyof typeof BuildingsSortingDtoHouseNumberEnum];
export const BuildingsSortingDtoLatEnum = {
    Asc: 'asc',
    Desc: 'desc'
} as const;

export type BuildingsSortingDtoLatEnum = typeof BuildingsSortingDtoLatEnum[keyof typeof BuildingsSortingDtoLatEnum];
export const BuildingsSortingDtoLonEnum = {
    Asc: 'asc',
    Desc: 'desc'
} as const;

export type BuildingsSortingDtoLonEnum = typeof BuildingsSortingDtoLonEnum[keyof typeof BuildingsSortingDtoLonEnum];
export const BuildingsSortingDtoCreatedAtEnum = {
    Asc: 'asc',
    Desc: 'desc'
} as const;

export type BuildingsSortingDtoCreatedAtEnum = typeof BuildingsSortingDtoCreatedAtEnum[keyof typeof BuildingsSortingDtoCreatedAtEnum];
export const BuildingsSortingDtoUpdatedAtEnum = {
    Asc: 'asc',
    Desc: 'desc'
} as const;

export type BuildingsSortingDtoUpdatedAtEnum = typeof BuildingsSortingDtoUpdatedAtEnum[keyof typeof BuildingsSortingDtoUpdatedAtEnum];


