/* tslint:disable */
/* eslint-disable */
/**
 * пожликбез.рф API
 * API спецификация пожликбез.рф
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateObjectDto
 */
export interface CreateObjectDto {
    /**
     * 
     * @type {string}
     * @memberof CreateObjectDto
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CreateObjectDto
     */
    sp2type: string;
    /**
     * 
     * @type {string}
     * @memberof CreateObjectDto
     */
    sp2name: string;
    /**
     * 
     * @type {string}
     * @memberof CreateObjectDto
     */
    sp2questions: string;
    /**
     * 
     * @type {number}
     * @memberof CreateObjectDto
     */
    upFloors: number;
    /**
     * 
     * @type {boolean}
     * @memberof CreateObjectDto
     */
    isUnderFloor: boolean;
    /**
     * 
     * @type {number}
     * @memberof CreateObjectDto
     */
    underFloors: number;
    /**
     * 
     * @type {number}
     * @memberof CreateObjectDto
     */
    fireRoomArea: number;
    /**
     * 
     * @type {number}
     * @memberof CreateObjectDto
     */
    tradeArea: number;
    /**
     * 
     * @type {boolean}
     * @memberof CreateObjectDto
     */
    blackTradeRooms: boolean;
    /**
     * 
     * @type {number}
     * @memberof CreateObjectDto
     */
    height: number;
    /**
     * 
     * @type {number}
     * @memberof CreateObjectDto
     */
    volume: number;
    /**
     * 
     * @type {string}
     * @memberof CreateObjectDto
     */
    _class: string;
    /**
     * 
     * @type {string}
     * @memberof CreateObjectDto
     */
    degree: string;
    /**
     * 
     * @type {string}
     * @memberof CreateObjectDto
     */
    address: string;
    /**
     * 
     * @type {string}
     * @memberof CreateObjectDto
     */
    typeOfBuild: string;
}

/**
 * Check if a given object implements the CreateObjectDto interface.
 */
export function instanceOfCreateObjectDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "sp2type" in value;
    isInstance = isInstance && "sp2name" in value;
    isInstance = isInstance && "sp2questions" in value;
    isInstance = isInstance && "upFloors" in value;
    isInstance = isInstance && "isUnderFloor" in value;
    isInstance = isInstance && "underFloors" in value;
    isInstance = isInstance && "fireRoomArea" in value;
    isInstance = isInstance && "tradeArea" in value;
    isInstance = isInstance && "blackTradeRooms" in value;
    isInstance = isInstance && "height" in value;
    isInstance = isInstance && "volume" in value;
    isInstance = isInstance && "_class" in value;
    isInstance = isInstance && "degree" in value;
    isInstance = isInstance && "address" in value;
    isInstance = isInstance && "typeOfBuild" in value;

    return isInstance;
}

export function CreateObjectDtoFromJSON(json: any): CreateObjectDto {
    return CreateObjectDtoFromJSONTyped(json, false);
}

export function CreateObjectDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateObjectDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'sp2type': json['sp2type'],
        'sp2name': json['sp2name'],
        'sp2questions': json['sp2questions'],
        'upFloors': json['upFloors'],
        'isUnderFloor': json['isUnderFloor'],
        'underFloors': json['underFloors'],
        'fireRoomArea': json['fireRoomArea'],
        'tradeArea': json['tradeArea'],
        'blackTradeRooms': json['blackTradeRooms'],
        'height': json['height'],
        'volume': json['volume'],
        '_class': json['class'],
        'degree': json['degree'],
        'address': json['address'],
        'typeOfBuild': json['typeOfBuild'],
    };
}

export function CreateObjectDtoToJSON(value?: CreateObjectDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'sp2type': value.sp2type,
        'sp2name': value.sp2name,
        'sp2questions': value.sp2questions,
        'upFloors': value.upFloors,
        'isUnderFloor': value.isUnderFloor,
        'underFloors': value.underFloors,
        'fireRoomArea': value.fireRoomArea,
        'tradeArea': value.tradeArea,
        'blackTradeRooms': value.blackTradeRooms,
        'height': value.height,
        'volume': value.volume,
        'class': value._class,
        'degree': value.degree,
        'address': value.address,
        'typeOfBuild': value.typeOfBuild,
    };
}

