/* tslint:disable */
/* eslint-disable */
/**
 * пожликбез.рф API
 * API спецификация пожликбез.рф
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateOwnerDto
 */
export interface CreateOwnerDto {
    /**
     * 
     * @type {string}
     * @memberof CreateOwnerDto
     */
    id: string;
}

/**
 * Check if a given object implements the CreateOwnerDto interface.
 */
export function instanceOfCreateOwnerDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;

    return isInstance;
}

export function CreateOwnerDtoFromJSON(json: any): CreateOwnerDto {
    return CreateOwnerDtoFromJSONTyped(json, false);
}

export function CreateOwnerDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateOwnerDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
    };
}

export function CreateOwnerDtoToJSON(value?: CreateOwnerDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
    };
}

