/* tslint:disable */
/* eslint-disable */
/**
 * Новосибирск BMW Клуб API
 * API спецификация api.bmw-nsk.ru
 *
 * The version of the OpenAPI document: 1.0
 * Contact: evist0@dblade.tech
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CreatePartnerDto
 */
export interface CreatePartnerDto {
    /**
     * 
     * @type {string}
     * @memberof CreatePartnerDto
     */
    'logo'?: string;
    /**
     * 
     * @type {string}
     * @memberof CreatePartnerDto
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof CreatePartnerDto
     */
    'url'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreatePartnerDto
     */
    'phone'?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof CreatePartnerDto
     */
    'servicePartner'?: boolean;
}

