/* tslint:disable */
/* eslint-disable */
/**
 * пожликбез.рф API
 * API спецификация пожликбез.рф
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Объект с указанным id не найден.
 * @export
 * @interface ObjectsControllerFindOne404Response
 */
export interface ObjectsControllerFindOne404Response {
    /**
     * 
     * @type {number}
     * @memberof ObjectsControllerFindOne404Response
     */
    statusCode: number;
    /**
     * 
     * @type {string}
     * @memberof ObjectsControllerFindOne404Response
     */
    message: string;
    /**
     * 
     * @type {string}
     * @memberof ObjectsControllerFindOne404Response
     */
    error?: string;
}

/**
 * Check if a given object implements the ObjectsControllerFindOne404Response interface.
 */
export function instanceOfObjectsControllerFindOne404Response(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "statusCode" in value;
    isInstance = isInstance && "message" in value;

    return isInstance;
}

export function ObjectsControllerFindOne404ResponseFromJSON(json: any): ObjectsControllerFindOne404Response {
    return ObjectsControllerFindOne404ResponseFromJSONTyped(json, false);
}

export function ObjectsControllerFindOne404ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ObjectsControllerFindOne404Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'statusCode': json['statusCode'],
        'message': json['message'],
        'error': !exists(json, 'error') ? undefined : json['error'],
    };
}

export function ObjectsControllerFindOne404ResponseToJSON(value?: ObjectsControllerFindOne404Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'statusCode': value.statusCode,
        'message': value.message,
        'error': value.error,
    };
}

