/* tslint:disable */
/* eslint-disable */
/**
 * пожликбез.рф API
 * API спецификация пожликбез.рф
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { OwnerEntity } from './OwnerEntity';
import {
    OwnerEntityFromJSON,
    OwnerEntityFromJSONTyped,
    OwnerEntityToJSON,
} from './OwnerEntity';

/**
 * 
 * @export
 * @interface ObjectsControllerGetOwners200Response
 */
export interface ObjectsControllerGetOwners200Response {
    /**
     * 
     * @type {Array<OwnerEntity>}
     * @memberof ObjectsControllerGetOwners200Response
     */
    data: Array<OwnerEntity>;
    /**
     * 
     * @type {number}
     * @memberof ObjectsControllerGetOwners200Response
     */
    total: number;
}

/**
 * Check if a given object implements the ObjectsControllerGetOwners200Response interface.
 */
export function instanceOfObjectsControllerGetOwners200Response(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;
    isInstance = isInstance && "total" in value;

    return isInstance;
}

export function ObjectsControllerGetOwners200ResponseFromJSON(json: any): ObjectsControllerGetOwners200Response {
    return ObjectsControllerGetOwners200ResponseFromJSONTyped(json, false);
}

export function ObjectsControllerGetOwners200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ObjectsControllerGetOwners200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(OwnerEntityFromJSON)),
        'total': json['total'],
    };
}

export function ObjectsControllerGetOwners200ResponseToJSON(value?: ObjectsControllerGetOwners200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': ((value.data as Array<any>).map(OwnerEntityToJSON)),
        'total': value.total,
    };
}

