/* tslint:disable */
/* eslint-disable */
/**
 * пожликбез.рф API
 * API спецификация пожликбез.рф
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ObjectEntity
 */
export interface ObjectEntity {
    /**
     * 
     * @type {number}
     * @memberof ObjectEntity
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof ObjectEntity
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ObjectEntity
     */
    sp2type: string;
    /**
     * 
     * @type {string}
     * @memberof ObjectEntity
     */
    sp2name: string;
    /**
     * 
     * @type {string}
     * @memberof ObjectEntity
     */
    sp2questions: string;
    /**
     * 
     * @type {number}
     * @memberof ObjectEntity
     */
    upFloors: number;
    /**
     * 
     * @type {boolean}
     * @memberof ObjectEntity
     */
    isUnderFloor: boolean;
    /**
     * 
     * @type {number}
     * @memberof ObjectEntity
     */
    underFloors: number;
    /**
     * 
     * @type {number}
     * @memberof ObjectEntity
     */
    fireRoomArea: number;
    /**
     * 
     * @type {number}
     * @memberof ObjectEntity
     */
    tradeArea: number;
    /**
     * 
     * @type {boolean}
     * @memberof ObjectEntity
     */
    blackTradeRooms: boolean;
    /**
     * 
     * @type {number}
     * @memberof ObjectEntity
     */
    height: number;
    /**
     * 
     * @type {number}
     * @memberof ObjectEntity
     */
    volume: number;
    /**
     * 
     * @type {string}
     * @memberof ObjectEntity
     */
    _class: string;
    /**
     * 
     * @type {string}
     * @memberof ObjectEntity
     */
    degree: string;
}

/**
 * Check if a given object implements the ObjectEntity interface.
 */
export function instanceOfObjectEntity(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "sp2type" in value;
    isInstance = isInstance && "sp2name" in value;
    isInstance = isInstance && "sp2questions" in value;
    isInstance = isInstance && "upFloors" in value;
    isInstance = isInstance && "isUnderFloor" in value;
    isInstance = isInstance && "underFloors" in value;
    isInstance = isInstance && "fireRoomArea" in value;
    isInstance = isInstance && "tradeArea" in value;
    isInstance = isInstance && "blackTradeRooms" in value;
    isInstance = isInstance && "height" in value;
    isInstance = isInstance && "volume" in value;
    isInstance = isInstance && "_class" in value;
    isInstance = isInstance && "degree" in value;

    return isInstance;
}

export function ObjectEntityFromJSON(json: any): ObjectEntity {
    return ObjectEntityFromJSONTyped(json, false);
}

export function ObjectEntityFromJSONTyped(json: any, ignoreDiscriminator: boolean): ObjectEntity {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'sp2type': json['sp2type'],
        'sp2name': json['sp2name'],
        'sp2questions': json['sp2questions'],
        'upFloors': json['upFloors'],
        'isUnderFloor': json['isUnderFloor'],
        'underFloors': json['underFloors'],
        'fireRoomArea': json['fireRoomArea'],
        'tradeArea': json['tradeArea'],
        'blackTradeRooms': json['blackTradeRooms'],
        'height': json['height'],
        'volume': json['volume'],
        '_class': json['class'],
        'degree': json['degree'],
    };
}

export function ObjectEntityToJSON(value?: ObjectEntity | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'sp2type': value.sp2type,
        'sp2name': value.sp2name,
        'sp2questions': value.sp2questions,
        'upFloors': value.upFloors,
        'isUnderFloor': value.isUnderFloor,
        'underFloors': value.underFloors,
        'fireRoomArea': value.fireRoomArea,
        'tradeArea': value.tradeArea,
        'blackTradeRooms': value.blackTradeRooms,
        'height': value.height,
        'volume': value.volume,
        'class': value._class,
        'degree': value.degree,
    };
}

