/* tslint:disable */
/* eslint-disable */
/**
 * пожликбез.рф API
 * API спецификация пожликбез.рф
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Нельзя удалить автора объекта.
 * @export
 * @interface ObjectsControllerRemoveOwner400Response
 */
export interface ObjectsControllerRemoveOwner400Response {
    /**
     * 
     * @type {number}
     * @memberof ObjectsControllerRemoveOwner400Response
     */
    statusCode: number;
    /**
     * 
     * @type {string}
     * @memberof ObjectsControllerRemoveOwner400Response
     */
    message: string;
    /**
     * 
     * @type {string}
     * @memberof ObjectsControllerRemoveOwner400Response
     */
    error?: string;
}

/**
 * Check if a given object implements the ObjectsControllerRemoveOwner400Response interface.
 */
export function instanceOfObjectsControllerRemoveOwner400Response(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "statusCode" in value;
    isInstance = isInstance && "message" in value;

    return isInstance;
}

export function ObjectsControllerRemoveOwner400ResponseFromJSON(json: any): ObjectsControllerRemoveOwner400Response {
    return ObjectsControllerRemoveOwner400ResponseFromJSONTyped(json, false);
}

export function ObjectsControllerRemoveOwner400ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ObjectsControllerRemoveOwner400Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'statusCode': json['statusCode'],
        'message': json['message'],
        'error': !exists(json, 'error') ? undefined : json['error'],
    };
}

export function ObjectsControllerRemoveOwner400ResponseToJSON(value?: ObjectsControllerRemoveOwner400Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'statusCode': value.statusCode,
        'message': value.message,
        'error': value.error,
    };
}

