/* tslint:disable */
/* eslint-disable */
/**
 * пожликбез.рф API
 * API спецификация пожликбез.рф
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Владелец с указанным id не найден.
 * @export
 * @interface ObjectsControllerRemoveOwner404Response
 */
export interface ObjectsControllerRemoveOwner404Response {
    /**
     * 
     * @type {number}
     * @memberof ObjectsControllerRemoveOwner404Response
     */
    statusCode: number;
    /**
     * 
     * @type {string}
     * @memberof ObjectsControllerRemoveOwner404Response
     */
    message: string;
    /**
     * 
     * @type {string}
     * @memberof ObjectsControllerRemoveOwner404Response
     */
    error?: string;
}

/**
 * Check if a given object implements the ObjectsControllerRemoveOwner404Response interface.
 */
export function instanceOfObjectsControllerRemoveOwner404Response(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "statusCode" in value;
    isInstance = isInstance && "message" in value;

    return isInstance;
}

export function ObjectsControllerRemoveOwner404ResponseFromJSON(json: any): ObjectsControllerRemoveOwner404Response {
    return ObjectsControllerRemoveOwner404ResponseFromJSONTyped(json, false);
}

export function ObjectsControllerRemoveOwner404ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ObjectsControllerRemoveOwner404Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'statusCode': json['statusCode'],
        'message': json['message'],
        'error': !exists(json, 'error') ? undefined : json['error'],
    };
}

export function ObjectsControllerRemoveOwner404ResponseToJSON(value?: ObjectsControllerRemoveOwner404Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'statusCode': value.statusCode,
        'message': value.message,
        'error': value.error,
    };
}

