/* tslint:disable */
/* eslint-disable */
/**
 * пожликбез.рф API
 * API спецификация пожликбез.рф
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ObjectEntity } from './ObjectEntity';
import {
    ObjectEntityFromJSON,
    ObjectEntityFromJSONTyped,
    ObjectEntityToJSON,
} from './ObjectEntity';

/**
 * 
 * @export
 * @interface ObjectsControllerFind200Response
 */
export interface ObjectsControllerFind200Response {
    /**
     * 
     * @type {Array<ObjectEntity>}
     * @memberof ObjectsControllerFind200Response
     */
    data: Array<ObjectEntity>;
    /**
     * 
     * @type {number}
     * @memberof ObjectsControllerFind200Response
     */
    total: number;
}

/**
 * Check if a given object implements the ObjectsControllerFind200Response interface.
 */
export function instanceOfObjectsControllerFind200Response(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;
    isInstance = isInstance && "total" in value;

    return isInstance;
}

export function ObjectsControllerFind200ResponseFromJSON(json: any): ObjectsControllerFind200Response {
    return ObjectsControllerFind200ResponseFromJSONTyped(json, false);
}

export function ObjectsControllerFind200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ObjectsControllerFind200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(ObjectEntityFromJSON)),
        'total': json['total'],
    };
}

export function ObjectsControllerFind200ResponseToJSON(value?: ObjectsControllerFind200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': ((value.data as Array<any>).map(ObjectEntityToJSON)),
        'total': value.total,
    };
}

