/* tslint:disable */
/* eslint-disable */
/**
 * пожликбез.рф API
 * API спецификация пожликбез.рф
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { OwnerEntity } from './OwnerEntity';
import {
    OwnerEntityFromJSON,
    OwnerEntityFromJSONTyped,
    OwnerEntityToJSON,
} from './OwnerEntity';

/**
 * 
 * @export
 * @interface ObjectsControllerGetOwners200ResponseAllOf
 */
export interface ObjectsControllerGetOwners200ResponseAllOf {
    /**
     * 
     * @type {Array<OwnerEntity>}
     * @memberof ObjectsControllerGetOwners200ResponseAllOf
     */
    data?: Array<OwnerEntity>;
}

/**
 * Check if a given object implements the ObjectsControllerGetOwners200ResponseAllOf interface.
 */
export function instanceOfObjectsControllerGetOwners200ResponseAllOf(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ObjectsControllerGetOwners200ResponseAllOfFromJSON(json: any): ObjectsControllerGetOwners200ResponseAllOf {
    return ObjectsControllerGetOwners200ResponseAllOfFromJSONTyped(json, false);
}

export function ObjectsControllerGetOwners200ResponseAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): ObjectsControllerGetOwners200ResponseAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': !exists(json, 'data') ? undefined : ((json['data'] as Array<any>).map(OwnerEntityFromJSON)),
    };
}

export function ObjectsControllerGetOwners200ResponseAllOfToJSON(value?: ObjectsControllerGetOwners200ResponseAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': value.data === undefined ? undefined : ((value.data as Array<any>).map(OwnerEntityToJSON)),
    };
}

