/* tslint:disable */
/* eslint-disable */
/**
 * пожликбез.рф API
 * API спецификация пожликбез.рф
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OwnerEntity
 */
export interface OwnerEntity {
    /**
     * 
     * @type {string}
     * @memberof OwnerEntity
     */
    id: string;
    /**
     * 
     * @type {boolean}
     * @memberof OwnerEntity
     */
    author?: boolean;
}

/**
 * Check if a given object implements the OwnerEntity interface.
 */
export function instanceOfOwnerEntity(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;

    return isInstance;
}

export function OwnerEntityFromJSON(json: any): OwnerEntity {
    return OwnerEntityFromJSONTyped(json, false);
}

export function OwnerEntityFromJSONTyped(json: any, ignoreDiscriminator: boolean): OwnerEntity {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'author': !exists(json, 'author') ? undefined : json['author'],
    };
}

export function OwnerEntityToJSON(value?: OwnerEntity | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'author': value.author,
    };
}

