/* tslint:disable */
/* eslint-disable */
/**
 * пожликбез.рф API
 * API спецификация пожликбез.рф
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PaginationResultDto
 */
export interface PaginationResultDto {
    /**
     * 
     * @type {Array<string>}
     * @memberof PaginationResultDto
     */
    data: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof PaginationResultDto
     */
    total: number;
}

/**
 * Check if a given object implements the PaginationResultDto interface.
 */
export function instanceOfPaginationResultDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;
    isInstance = isInstance && "total" in value;

    return isInstance;
}

export function PaginationResultDtoFromJSON(json: any): PaginationResultDto {
    return PaginationResultDtoFromJSONTyped(json, false);
}

export function PaginationResultDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginationResultDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': json['data'],
        'total': json['total'],
    };
}

export function PaginationResultDtoToJSON(value?: PaginationResultDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': value.data,
        'total': value.total,
    };
}

