/* tslint:disable */
/* eslint-disable */
/**
 * Новосибирск BMW Клуб API
 * API спецификация api.bmw-nsk.ru
 *
 * The version of the OpenAPI document: 1.0
 * Contact: evist0@dblade.tech
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PartnersSortingDto
 */
export interface PartnersSortingDto {
    /**
     * 
     * @type {string}
     * @memberof PartnersSortingDto
     */
    'id'?: PartnersSortingDtoIdEnum;
    /**
     * 
     * @type {string}
     * @memberof PartnersSortingDto
     */
    'logo'?: PartnersSortingDtoLogoEnum;
    /**
     * 
     * @type {string}
     * @memberof PartnersSortingDto
     */
    'name'?: PartnersSortingDtoNameEnum;
    /**
     * 
     * @type {string}
     * @memberof PartnersSortingDto
     */
    'url'?: PartnersSortingDtoUrlEnum;
    /**
     * 
     * @type {string}
     * @memberof PartnersSortingDto
     */
    'phone'?: PartnersSortingDtoPhoneEnum;
    /**
     * 
     * @type {string}
     * @memberof PartnersSortingDto
     */
    'servicePartner'?: PartnersSortingDtoServicePartnerEnum;
    /**
     * 
     * @type {string}
     * @memberof PartnersSortingDto
     */
    'createdAt'?: PartnersSortingDtoCreatedAtEnum;
    /**
     * 
     * @type {string}
     * @memberof PartnersSortingDto
     */
    'updatedAt'?: PartnersSortingDtoUpdatedAtEnum;
}

export const PartnersSortingDtoIdEnum = {
    Asc: 'asc',
    Desc: 'desc'
} as const;

export type PartnersSortingDtoIdEnum = typeof PartnersSortingDtoIdEnum[keyof typeof PartnersSortingDtoIdEnum];
export const PartnersSortingDtoLogoEnum = {
    Asc: 'asc',
    Desc: 'desc'
} as const;

export type PartnersSortingDtoLogoEnum = typeof PartnersSortingDtoLogoEnum[keyof typeof PartnersSortingDtoLogoEnum];
export const PartnersSortingDtoNameEnum = {
    Asc: 'asc',
    Desc: 'desc'
} as const;

export type PartnersSortingDtoNameEnum = typeof PartnersSortingDtoNameEnum[keyof typeof PartnersSortingDtoNameEnum];
export const PartnersSortingDtoUrlEnum = {
    Asc: 'asc',
    Desc: 'desc'
} as const;

export type PartnersSortingDtoUrlEnum = typeof PartnersSortingDtoUrlEnum[keyof typeof PartnersSortingDtoUrlEnum];
export const PartnersSortingDtoPhoneEnum = {
    Asc: 'asc',
    Desc: 'desc'
} as const;

export type PartnersSortingDtoPhoneEnum = typeof PartnersSortingDtoPhoneEnum[keyof typeof PartnersSortingDtoPhoneEnum];
export const PartnersSortingDtoServicePartnerEnum = {
    Asc: 'asc',
    Desc: 'desc'
} as const;

export type PartnersSortingDtoServicePartnerEnum = typeof PartnersSortingDtoServicePartnerEnum[keyof typeof PartnersSortingDtoServicePartnerEnum];
export const PartnersSortingDtoCreatedAtEnum = {
    Asc: 'asc',
    Desc: 'desc'
} as const;

export type PartnersSortingDtoCreatedAtEnum = typeof PartnersSortingDtoCreatedAtEnum[keyof typeof PartnersSortingDtoCreatedAtEnum];
export const PartnersSortingDtoUpdatedAtEnum = {
    Asc: 'asc',
    Desc: 'desc'
} as const;

export type PartnersSortingDtoUpdatedAtEnum = typeof PartnersSortingDtoUpdatedAtEnum[keyof typeof PartnersSortingDtoUpdatedAtEnum];


