/* tslint:disable */
/* eslint-disable */
/**
 * Новосибирск BMW Клуб API
 * API спецификация api.bmw-nsk.ru
 *
 * The version of the OpenAPI document: 1.0
 * Contact: evist0@dblade.tech
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { PartnerEntity } from './partner-entity';

/**
 * 
 * @export
 * @interface PartnersControllerFind200ResponseAllOf
 */
export interface PartnersControllerFind200ResponseAllOf {
    /**
     * 
     * @type {Array<PartnerEntity>}
     * @memberof PartnersControllerFind200ResponseAllOf
     */
    'data'?: Array<PartnerEntity>;
}

