/* tslint:disable */
/* eslint-disable */
/**
 * Новосибирск BMW Клуб API
 * API спецификация api.bmw-nsk.ru
 *
 * The version of the OpenAPI document: 1.0
 * Contact: evist0@dblade.tech
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Недостаточно прав.
 * @export
 * @interface PartnersControllerFind403Response
 */
export interface PartnersControllerFind403Response {
    /**
     * 
     * @type {number}
     * @memberof PartnersControllerFind403Response
     */
    'statusCode': number;
    /**
     * 
     * @type {string}
     * @memberof PartnersControllerFind403Response
     */
    'message': string;
    /**
     * 
     * @type {string}
     * @memberof PartnersControllerFind403Response
     */
    'error'?: string;
}

