/* tslint:disable */
/* eslint-disable */
/**
 * Новосибирск BMW Клуб API
 * API спецификация api.bmw-nsk.ru
 *
 * The version of the OpenAPI document: 1.0
 * Contact: evist0@dblade.tech
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { PaginatedEntity } from './paginated-entity';
// May contain unused imports in some cases
// @ts-ignore
import { PartnerEntity } from './partner-entity';
// May contain unused imports in some cases
// @ts-ignore
import { PartnersControllerFind200ResponseAllOf } from './partners-controller-find200-response-all-of';

/**
 * @type PartnersControllerFind200Response
 * @export
 */
export type PartnersControllerFind200Response = PaginatedEntity & PartnersControllerFind200ResponseAllOf;


