/* tslint:disable */
/* eslint-disable */
/**
 * Новосибирск BMW Клуб API
 * API спецификация api.bmw-nsk.ru
 *
 * The version of the OpenAPI document: 1.0
 * Contact: evist0@dblade.tech
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PartnerEntity
 */
export interface PartnerEntity {
    /**
     * 
     * @type {string}
     * @memberof PartnerEntity
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof PartnerEntity
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof PartnerEntity
     */
    'logo': string | null;
    /**
     * 
     * @type {string}
     * @memberof PartnerEntity
     */
    'site': string | null;
    /**
     * 
     * @type {string}
     * @memberof PartnerEntity
     */
    'createdAt': string;
    /**
     * 
     * @type {string}
     * @memberof PartnerEntity
     */
    'updatedAt': string;
}

