/* tslint:disable */
/* eslint-disable */
/**
 * Пожликбез APIирск BMW Клуб API
 * API спецификация api.bmw-nsk.ru
 *
 * The version of the OpenAPI document: 1.0
 * Contact: kurskatm@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { PaginationResultDto } from './pagination-result-dto';
// May contain unused imports in some cases
// @ts-ignore
import { PartnerEntity } from './partner-entity';
// May contain unused imports in some cases
// @ts-ignore
import { PartnersControllerFindAll200ResponseAllOf } from './partners-controller-find-all200-response-all-of';

/**
 * @type PartnersControllerFindAll200Response
 * @export
 */
export type PartnersControllerFindAll200Response = PaginationResultDto & PartnersControllerFindAll200ResponseAllOf;


