/* tslint:disable */
/* eslint-disable */
/**
 * Новосибирск BMW Клуб API
 * API спецификация api.bmw-nsk.ru
 *
 * The version of the OpenAPI document: 1.0
 * Contact: evist0@dblade.tech
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { BuildingEntityCategoriesInner } from './building-entity-categories-inner';
// May contain unused imports in some cases
// @ts-ignore
import { PostEntityAssetsInner } from './post-entity-assets-inner';

/**
 * 
 * @export
 * @interface PostEntity
 */
export interface PostEntity {
    /**
     * 
     * @type {string}
     * @memberof PostEntity
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof PostEntity
     */
    'title': string;
    /**
     * 
     * @type {string}
     * @memberof PostEntity
     */
    'description': string;
    /**
     * 
     * @type {string}
     * @memberof PostEntity
     */
    'previewUrl': string | null;
    /**
     * 
     * @type {string}
     * @memberof PostEntity
     */
    'content': string;
    /**
     * 
     * @type {Array<PostEntityAssetsInner>}
     * @memberof PostEntity
     */
    'assets': Array<PostEntityAssetsInner>;
    /**
     * 
     * @type {Array<BuildingEntityCategoriesInner>}
     * @memberof PostEntity
     */
    'categories': Array<BuildingEntityCategoriesInner>;
    /**
     * 
     * @type {boolean}
     * @memberof PostEntity
     */
    'published'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof PostEntity
     */
    'createdAt': string;
    /**
     * 
     * @type {string}
     * @memberof PostEntity
     */
    'updatedAt': string;
}

