/* tslint:disable */
/* eslint-disable */
/**
 * Новосибирск BMW Клуб API
 * API спецификация api.bmw-nsk.ru
 *
 * The version of the OpenAPI document: 1.0
 * Contact: evist0@dblade.tech
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PostsSortingDto
 */
export interface PostsSortingDto {
    /**
     * 
     * @type {string}
     * @memberof PostsSortingDto
     */
    'id'?: PostsSortingDtoIdEnum;
    /**
     * 
     * @type {string}
     * @memberof PostsSortingDto
     */
    'title'?: PostsSortingDtoTitleEnum;
    /**
     * 
     * @type {string}
     * @memberof PostsSortingDto
     */
    'description'?: PostsSortingDtoDescriptionEnum;
    /**
     * 
     * @type {string}
     * @memberof PostsSortingDto
     */
    'previewUrl'?: PostsSortingDtoPreviewUrlEnum;
    /**
     * 
     * @type {string}
     * @memberof PostsSortingDto
     */
    'published'?: PostsSortingDtoPublishedEnum;
    /**
     * 
     * @type {string}
     * @memberof PostsSortingDto
     */
    'createdAt'?: PostsSortingDtoCreatedAtEnum;
    /**
     * 
     * @type {string}
     * @memberof PostsSortingDto
     */
    'updatedAt'?: PostsSortingDtoUpdatedAtEnum;
}

export const PostsSortingDtoIdEnum = {
    Asc: 'asc',
    Desc: 'desc'
} as const;

export type PostsSortingDtoIdEnum = typeof PostsSortingDtoIdEnum[keyof typeof PostsSortingDtoIdEnum];
export const PostsSortingDtoTitleEnum = {
    Asc: 'asc',
    Desc: 'desc'
} as const;

export type PostsSortingDtoTitleEnum = typeof PostsSortingDtoTitleEnum[keyof typeof PostsSortingDtoTitleEnum];
export const PostsSortingDtoDescriptionEnum = {
    Asc: 'asc',
    Desc: 'desc'
} as const;

export type PostsSortingDtoDescriptionEnum = typeof PostsSortingDtoDescriptionEnum[keyof typeof PostsSortingDtoDescriptionEnum];
export const PostsSortingDtoPreviewUrlEnum = {
    Asc: 'asc',
    Desc: 'desc'
} as const;

export type PostsSortingDtoPreviewUrlEnum = typeof PostsSortingDtoPreviewUrlEnum[keyof typeof PostsSortingDtoPreviewUrlEnum];
export const PostsSortingDtoPublishedEnum = {
    Asc: 'asc',
    Desc: 'desc'
} as const;

export type PostsSortingDtoPublishedEnum = typeof PostsSortingDtoPublishedEnum[keyof typeof PostsSortingDtoPublishedEnum];
export const PostsSortingDtoCreatedAtEnum = {
    Asc: 'asc',
    Desc: 'desc'
} as const;

export type PostsSortingDtoCreatedAtEnum = typeof PostsSortingDtoCreatedAtEnum[keyof typeof PostsSortingDtoCreatedAtEnum];
export const PostsSortingDtoUpdatedAtEnum = {
    Asc: 'asc',
    Desc: 'desc'
} as const;

export type PostsSortingDtoUpdatedAtEnum = typeof PostsSortingDtoUpdatedAtEnum[keyof typeof PostsSortingDtoUpdatedAtEnum];


