/* tslint:disable */
/* eslint-disable */
/**
 * Новосибирск BMW Клуб API
 * API спецификация api.bmw-nsk.ru
 *
 * The version of the OpenAPI document: 1.0
 * Contact: evist0@dblade.tech
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PostCategoriesSortingDto
 */
export interface PostCategoriesSortingDto {
    /**
     * 
     * @type {string}
     * @memberof PostCategoriesSortingDto
     */
    'id'?: PostCategoriesSortingDtoIdEnum;
    /**
     * 
     * @type {string}
     * @memberof PostCategoriesSortingDto
     */
    'name'?: PostCategoriesSortingDtoNameEnum;
    /**
     * 
     * @type {string}
     * @memberof PostCategoriesSortingDto
     */
    'lowerName'?: PostCategoriesSortingDtoLowerNameEnum;
    /**
     * 
     * @type {string}
     * @memberof PostCategoriesSortingDto
     */
    'createdAt'?: PostCategoriesSortingDtoCreatedAtEnum;
    /**
     * 
     * @type {string}
     * @memberof PostCategoriesSortingDto
     */
    'updatedAt'?: PostCategoriesSortingDtoUpdatedAtEnum;
}

export const PostCategoriesSortingDtoIdEnum = {
    Asc: 'asc',
    Desc: 'desc'
} as const;

export type PostCategoriesSortingDtoIdEnum = typeof PostCategoriesSortingDtoIdEnum[keyof typeof PostCategoriesSortingDtoIdEnum];
export const PostCategoriesSortingDtoNameEnum = {
    Asc: 'asc',
    Desc: 'desc'
} as const;

export type PostCategoriesSortingDtoNameEnum = typeof PostCategoriesSortingDtoNameEnum[keyof typeof PostCategoriesSortingDtoNameEnum];
export const PostCategoriesSortingDtoLowerNameEnum = {
    Asc: 'asc',
    Desc: 'desc'
} as const;

export type PostCategoriesSortingDtoLowerNameEnum = typeof PostCategoriesSortingDtoLowerNameEnum[keyof typeof PostCategoriesSortingDtoLowerNameEnum];
export const PostCategoriesSortingDtoCreatedAtEnum = {
    Asc: 'asc',
    Desc: 'desc'
} as const;

export type PostCategoriesSortingDtoCreatedAtEnum = typeof PostCategoriesSortingDtoCreatedAtEnum[keyof typeof PostCategoriesSortingDtoCreatedAtEnum];
export const PostCategoriesSortingDtoUpdatedAtEnum = {
    Asc: 'asc',
    Desc: 'desc'
} as const;

export type PostCategoriesSortingDtoUpdatedAtEnum = typeof PostCategoriesSortingDtoUpdatedAtEnum[keyof typeof PostCategoriesSortingDtoUpdatedAtEnum];


