/* tslint:disable */
/* eslint-disable */
/**
 * Новосибирск BMW Клуб API
 * API спецификация api.bmw-nsk.ru
 *
 * The version of the OpenAPI document: 1.0
 * Contact: evist0@dblade.tech
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { PostCategoryEntity } from './post-category-entity';

/**
 * 
 * @export
 * @interface PostCategoriesControllerFind200ResponseAllOf
 */
export interface PostCategoriesControllerFind200ResponseAllOf {
    /**
     * 
     * @type {Array<PostCategoryEntity>}
     * @memberof PostCategoriesControllerFind200ResponseAllOf
     */
    'data'?: Array<PostCategoryEntity>;
}

