/* tslint:disable */
/* eslint-disable */
/**
 * Новосибирск BMW Клуб API
 * API спецификация api.bmw-nsk.ru
 *
 * The version of the OpenAPI document: 1.0
 * Contact: evist0@dblade.tech
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { BuildingEntityCategoriesInner } from './building-entity-categories-inner';

/**
 * 
 * @export
 * @interface PublicPostPreviewEntity
 */
export interface PublicPostPreviewEntity {
    /**
     * 
     * @type {string}
     * @memberof PublicPostPreviewEntity
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof PublicPostPreviewEntity
     */
    'title': string;
    /**
     * 
     * @type {string}
     * @memberof PublicPostPreviewEntity
     */
    'description': string;
    /**
     * 
     * @type {string}
     * @memberof PublicPostPreviewEntity
     */
    'previewUrl': string | null;
    /**
     * 
     * @type {Array<BuildingEntityCategoriesInner>}
     * @memberof PublicPostPreviewEntity
     */
    'categories': Array<BuildingEntityCategoriesInner>;
    /**
     * 
     * @type {string}
     * @memberof PublicPostPreviewEntity
     */
    'createdAt': string;
    /**
     * 
     * @type {string}
     * @memberof PublicPostPreviewEntity
     */
    'updatedAt': string;
}

