/* tslint:disable */
/* eslint-disable */
/**
 * Новосибирск BMW Клуб API
 * API спецификация api.bmw-nsk.ru
 *
 * The version of the OpenAPI document: 1.0
 * Contact: evist0@dblade.tech
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { PublicPostPreviewEntity } from './public-post-preview-entity';

/**
 * 
 * @export
 * @interface PublicControllerPosts200ResponseAllOf
 */
export interface PublicControllerPosts200ResponseAllOf {
    /**
     * 
     * @type {Array<PublicPostPreviewEntity>}
     * @memberof PublicControllerPosts200ResponseAllOf
     */
    'data'?: Array<PublicPostPreviewEntity>;
}

