/* tslint:disable */
/* eslint-disable */
/**
 * Новосибирск BMW Клуб API
 * API спецификация api.bmw-nsk.ru
 *
 * The version of the OpenAPI document: 1.0
 * Contact: evist0@dblade.tech
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UpdateBuildingDto
 */
export interface UpdateBuildingDto {
    /**
     * 
     * @type {string}
     * @memberof UpdateBuildingDto
     */
    'partnerId'?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateBuildingDto
     */
    'phone'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateBuildingDto
     */
    'city'?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateBuildingDto
     */
    'district'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateBuildingDto
     */
    'street'?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateBuildingDto
     */
    'houseNumber'?: string;
    /**
     * 
     * @type {number}
     * @memberof UpdateBuildingDto
     */
    'lat'?: number;
    /**
     * 
     * @type {number}
     * @memberof UpdateBuildingDto
     */
    'lon'?: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof UpdateBuildingDto
     */
    'categories'?: Array<string>;
}

