/* tslint:disable */
/* eslint-disable */
/**
 * Новосибирск BMW Клуб API
 * API спецификация api.bmw-nsk.ru
 *
 * The version of the OpenAPI document: 1.0
 * Contact: evist0@dblade.tech
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UpdateBuildingOfferDto
 */
export interface UpdateBuildingOfferDto {
    /**
     * 
     * @type {string}
     * @memberof UpdateBuildingOfferDto
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateBuildingOfferDto
     */
    'description'?: string;
}

