/* tslint:disable */
/* eslint-disable */
/**
 * Новосибирск BMW Клуб API
 * API спецификация api.bmw-nsk.ru
 *
 * The version of the OpenAPI document: 1.0
 * Contact: evist0@dblade.tech
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UserEntity
 */
export interface UserEntity {
    /**
     * 
     * @type {string}
     * @memberof UserEntity
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof UserEntity
     */
    'username': string | null;
    /**
     * 
     * @type {string}
     * @memberof UserEntity
     */
    'primaryEmail': string | null;
    /**
     * 
     * @type {string}
     * @memberof UserEntity
     */
    'primaryPhone': string | null;
    /**
     * 
     * @type {string}
     * @memberof UserEntity
     */
    'name': string | null;
    /**
     * 
     * @type {string}
     * @memberof UserEntity
     */
    'avatar': string | null;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof UserEntity
     */
    'customData': { [key: string]: any; };
    /**
     * 
     * @type {number}
     * @memberof UserEntity
     */
    'createdAt': number;
    /**
     * 
     * @type {boolean}
     * @memberof UserEntity
     */
    'isSuspended': boolean;
}

