/* tslint:disable */
/* eslint-disable */
/**
 * Новосибирск BMW Клуб API
 * API спецификация api.bmw-nsk.ru
 *
 * The version of the OpenAPI document: 1.0
 * Contact: evist0@dblade.tech
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export * from './api/building-categories-api';
export * from './api/building-offers-api';
export * from './api/buildings-api';
export * from './api/categories-on-buildings-api';
export * from './api/common-api';
export * from './api/partners-api';
export * from './api/post-categories-api';
export * from './api/posts-api';
export * from './api/public-api';
export * from './api/users-api';

