/* tslint:disable */
/* eslint-disable */
/**
 * Новосибирск BMW Клуб API
 * API спецификация api.bmw-nsk.ru
 *
 * The version of the OpenAPI document: 1.0
 * Contact: evist0@dblade.tech
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { BuildingEntity } from '../models';
// @ts-ignore
import { BuildingsControllerCreate404Response } from '../models';
// @ts-ignore
import { BuildingsControllerFind200Response } from '../models';
// @ts-ignore
import { BuildingsControllerFindOne404Response } from '../models';
// @ts-ignore
import { BuildingsSortingDto } from '../models';
// @ts-ignore
import { CreateBuildingDto } from '../models';
// @ts-ignore
import { PaginationDto } from '../models';
// @ts-ignore
import { PartnersControllerFind400Response } from '../models';
// @ts-ignore
import { PartnersControllerFind403Response } from '../models';
// @ts-ignore
import { PartnersControllerFindOne404Response } from '../models';
// @ts-ignore
import { UpdateBuildingDto } from '../models';
// @ts-ignore
import { UploadControllerUpload401Response } from '../models';
/**
 * BuildingsApi - axios parameter creator
 * @export
 */
export const BuildingsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Создает новый филиал.
         * @param {CreateBuildingDto} createBuildingDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        buildingsControllerCreate: async (createBuildingDto: CreateBuildingDto, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'createBuildingDto' is not null or undefined
            assertParamExists('buildingsControllerCreate', 'createBuildingDto', createBuildingDto)
            const localVarPath = `/buildings`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createBuildingDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Возвращает список филиалов.
         * @param {PaginationDto} [pagination] 
         * @param {BuildingsSortingDto} [sorting] 
         * @param {string} [phone] 
         * @param {string} [city] 
         * @param {string} [district] 
         * @param {string} [street] 
         * @param {string} [houseNumber] 
         * @param {string} [partnerId] 
         * @param {Array<string>} [categories] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        buildingsControllerFind: async (pagination?: PaginationDto, sorting?: BuildingsSortingDto, phone?: string, city?: string, district?: string, street?: string, houseNumber?: string, partnerId?: string, categories?: Array<string>, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/buildings`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (pagination !== undefined) {
                localVarQueryParameter['pagination'] = pagination;
            }

            if (sorting !== undefined) {
                localVarQueryParameter['sorting'] = sorting;
            }

            if (phone !== undefined) {
                localVarQueryParameter['phone'] = phone;
            }

            if (city !== undefined) {
                localVarQueryParameter['city'] = city;
            }

            if (district !== undefined) {
                localVarQueryParameter['district'] = district;
            }

            if (street !== undefined) {
                localVarQueryParameter['street'] = street;
            }

            if (houseNumber !== undefined) {
                localVarQueryParameter['houseNumber'] = houseNumber;
            }

            if (partnerId !== undefined) {
                localVarQueryParameter['partnerId'] = partnerId;
            }

            if (categories) {
                localVarQueryParameter['categories'] = categories;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Возвращает указанный филиал.
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        buildingsControllerFindOne: async (id: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('buildingsControllerFindOne', 'id', id)
            const localVarPath = `/buildings/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Удаляет указанный филиал.
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        buildingsControllerRemove: async (id: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('buildingsControllerRemove', 'id', id)
            const localVarPath = `/buildings/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Обновляет указанный филиал.
         * @param {string} id 
         * @param {UpdateBuildingDto} updateBuildingDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        buildingsControllerUpdate: async (id: string, updateBuildingDto: UpdateBuildingDto, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('buildingsControllerUpdate', 'id', id)
            // verify required parameter 'updateBuildingDto' is not null or undefined
            assertParamExists('buildingsControllerUpdate', 'updateBuildingDto', updateBuildingDto)
            const localVarPath = `/buildings/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updateBuildingDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * BuildingsApi - functional programming interface
 * @export
 */
export const BuildingsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = BuildingsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Создает новый филиал.
         * @param {CreateBuildingDto} createBuildingDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async buildingsControllerCreate(createBuildingDto: CreateBuildingDto, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BuildingEntity>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.buildingsControllerCreate(createBuildingDto, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Возвращает список филиалов.
         * @param {PaginationDto} [pagination] 
         * @param {BuildingsSortingDto} [sorting] 
         * @param {string} [phone] 
         * @param {string} [city] 
         * @param {string} [district] 
         * @param {string} [street] 
         * @param {string} [houseNumber] 
         * @param {string} [partnerId] 
         * @param {Array<string>} [categories] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async buildingsControllerFind(pagination?: PaginationDto, sorting?: BuildingsSortingDto, phone?: string, city?: string, district?: string, street?: string, houseNumber?: string, partnerId?: string, categories?: Array<string>, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BuildingsControllerFind200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.buildingsControllerFind(pagination, sorting, phone, city, district, street, houseNumber, partnerId, categories, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Возвращает указанный филиал.
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async buildingsControllerFindOne(id: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BuildingEntity>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.buildingsControllerFindOne(id, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Удаляет указанный филиал.
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async buildingsControllerRemove(id: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BuildingEntity>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.buildingsControllerRemove(id, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Обновляет указанный филиал.
         * @param {string} id 
         * @param {UpdateBuildingDto} updateBuildingDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async buildingsControllerUpdate(id: string, updateBuildingDto: UpdateBuildingDto, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BuildingEntity>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.buildingsControllerUpdate(id, updateBuildingDto, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * BuildingsApi - factory interface
 * @export
 */
export const BuildingsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = BuildingsApiFp(configuration)
    return {
        /**
         * 
         * @summary Создает новый филиал.
         * @param {BuildingsApiBuildingsControllerCreateRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        buildingsControllerCreate(requestParameters: BuildingsApiBuildingsControllerCreateRequest, options?: AxiosRequestConfig): AxiosPromise<BuildingEntity> {
            return localVarFp.buildingsControllerCreate(requestParameters.createBuildingDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Возвращает список филиалов.
         * @param {BuildingsApiBuildingsControllerFindRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        buildingsControllerFind(requestParameters: BuildingsApiBuildingsControllerFindRequest = {}, options?: AxiosRequestConfig): AxiosPromise<BuildingsControllerFind200Response> {
            return localVarFp.buildingsControllerFind(requestParameters.pagination, requestParameters.sorting, requestParameters.phone, requestParameters.city, requestParameters.district, requestParameters.street, requestParameters.houseNumber, requestParameters.partnerId, requestParameters.categories, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Возвращает указанный филиал.
         * @param {BuildingsApiBuildingsControllerFindOneRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        buildingsControllerFindOne(requestParameters: BuildingsApiBuildingsControllerFindOneRequest, options?: AxiosRequestConfig): AxiosPromise<BuildingEntity> {
            return localVarFp.buildingsControllerFindOne(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Удаляет указанный филиал.
         * @param {BuildingsApiBuildingsControllerRemoveRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        buildingsControllerRemove(requestParameters: BuildingsApiBuildingsControllerRemoveRequest, options?: AxiosRequestConfig): AxiosPromise<BuildingEntity> {
            return localVarFp.buildingsControllerRemove(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Обновляет указанный филиал.
         * @param {BuildingsApiBuildingsControllerUpdateRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        buildingsControllerUpdate(requestParameters: BuildingsApiBuildingsControllerUpdateRequest, options?: AxiosRequestConfig): AxiosPromise<BuildingEntity> {
            return localVarFp.buildingsControllerUpdate(requestParameters.id, requestParameters.updateBuildingDto, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for buildingsControllerCreate operation in BuildingsApi.
 * @export
 * @interface BuildingsApiBuildingsControllerCreateRequest
 */
export interface BuildingsApiBuildingsControllerCreateRequest {
    /**
     * 
     * @type {CreateBuildingDto}
     * @memberof BuildingsApiBuildingsControllerCreate
     */
    readonly createBuildingDto: CreateBuildingDto
}

/**
 * Request parameters for buildingsControllerFind operation in BuildingsApi.
 * @export
 * @interface BuildingsApiBuildingsControllerFindRequest
 */
export interface BuildingsApiBuildingsControllerFindRequest {
    /**
     * 
     * @type {PaginationDto}
     * @memberof BuildingsApiBuildingsControllerFind
     */
    readonly pagination?: PaginationDto

    /**
     * 
     * @type {BuildingsSortingDto}
     * @memberof BuildingsApiBuildingsControllerFind
     */
    readonly sorting?: BuildingsSortingDto

    /**
     * 
     * @type {string}
     * @memberof BuildingsApiBuildingsControllerFind
     */
    readonly phone?: string

    /**
     * 
     * @type {string}
     * @memberof BuildingsApiBuildingsControllerFind
     */
    readonly city?: string

    /**
     * 
     * @type {string}
     * @memberof BuildingsApiBuildingsControllerFind
     */
    readonly district?: string

    /**
     * 
     * @type {string}
     * @memberof BuildingsApiBuildingsControllerFind
     */
    readonly street?: string

    /**
     * 
     * @type {string}
     * @memberof BuildingsApiBuildingsControllerFind
     */
    readonly houseNumber?: string

    /**
     * 
     * @type {string}
     * @memberof BuildingsApiBuildingsControllerFind
     */
    readonly partnerId?: string

    /**
     * 
     * @type {Array<string>}
     * @memberof BuildingsApiBuildingsControllerFind
     */
    readonly categories?: Array<string>
}

/**
 * Request parameters for buildingsControllerFindOne operation in BuildingsApi.
 * @export
 * @interface BuildingsApiBuildingsControllerFindOneRequest
 */
export interface BuildingsApiBuildingsControllerFindOneRequest {
    /**
     * 
     * @type {string}
     * @memberof BuildingsApiBuildingsControllerFindOne
     */
    readonly id: string
}

/**
 * Request parameters for buildingsControllerRemove operation in BuildingsApi.
 * @export
 * @interface BuildingsApiBuildingsControllerRemoveRequest
 */
export interface BuildingsApiBuildingsControllerRemoveRequest {
    /**
     * 
     * @type {string}
     * @memberof BuildingsApiBuildingsControllerRemove
     */
    readonly id: string
}

/**
 * Request parameters for buildingsControllerUpdate operation in BuildingsApi.
 * @export
 * @interface BuildingsApiBuildingsControllerUpdateRequest
 */
export interface BuildingsApiBuildingsControllerUpdateRequest {
    /**
     * 
     * @type {string}
     * @memberof BuildingsApiBuildingsControllerUpdate
     */
    readonly id: string

    /**
     * 
     * @type {UpdateBuildingDto}
     * @memberof BuildingsApiBuildingsControllerUpdate
     */
    readonly updateBuildingDto: UpdateBuildingDto
}

/**
 * BuildingsApi - object-oriented interface
 * @export
 * @class BuildingsApi
 * @extends {BaseAPI}
 */
export class BuildingsApi extends BaseAPI {
    /**
     * 
     * @summary Создает новый филиал.
     * @param {BuildingsApiBuildingsControllerCreateRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BuildingsApi
     */
    public buildingsControllerCreate(requestParameters: BuildingsApiBuildingsControllerCreateRequest, options?: AxiosRequestConfig) {
        return BuildingsApiFp(this.configuration).buildingsControllerCreate(requestParameters.createBuildingDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Возвращает список филиалов.
     * @param {BuildingsApiBuildingsControllerFindRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BuildingsApi
     */
    public buildingsControllerFind(requestParameters: BuildingsApiBuildingsControllerFindRequest = {}, options?: AxiosRequestConfig) {
        return BuildingsApiFp(this.configuration).buildingsControllerFind(requestParameters.pagination, requestParameters.sorting, requestParameters.phone, requestParameters.city, requestParameters.district, requestParameters.street, requestParameters.houseNumber, requestParameters.partnerId, requestParameters.categories, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Возвращает указанный филиал.
     * @param {BuildingsApiBuildingsControllerFindOneRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BuildingsApi
     */
    public buildingsControllerFindOne(requestParameters: BuildingsApiBuildingsControllerFindOneRequest, options?: AxiosRequestConfig) {
        return BuildingsApiFp(this.configuration).buildingsControllerFindOne(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Удаляет указанный филиал.
     * @param {BuildingsApiBuildingsControllerRemoveRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BuildingsApi
     */
    public buildingsControllerRemove(requestParameters: BuildingsApiBuildingsControllerRemoveRequest, options?: AxiosRequestConfig) {
        return BuildingsApiFp(this.configuration).buildingsControllerRemove(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Обновляет указанный филиал.
     * @param {BuildingsApiBuildingsControllerUpdateRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BuildingsApi
     */
    public buildingsControllerUpdate(requestParameters: BuildingsApiBuildingsControllerUpdateRequest, options?: AxiosRequestConfig) {
        return BuildingsApiFp(this.configuration).buildingsControllerUpdate(requestParameters.id, requestParameters.updateBuildingDto, options).then((request) => request(this.axios, this.basePath));
    }
}
