/* tslint:disable */
/* eslint-disable */
/**
 * Новосибирск BMW Клуб API
 * API спецификация api.bmw-nsk.ru
 *
 * The version of the OpenAPI document: 1.0
 * Contact: evist0@dblade.tech
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { BuildingsArrayInner } from '../models';
/**
 * PublicBuildingsApi - axios parameter creator
 * @export
 */
export const PublicBuildingsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Возвращает список заведений от координат.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        publicControllerFindAll: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/buildings`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * PublicBuildingsApi - functional programming interface
 * @export
 */
export const PublicBuildingsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = PublicBuildingsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Возвращает список заведений от координат.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async publicControllerFindAll(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<BuildingsArrayInner>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.publicControllerFindAll(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * PublicBuildingsApi - factory interface
 * @export
 */
export const PublicBuildingsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = PublicBuildingsApiFp(configuration)
    return {
        /**
         * 
         * @summary Возвращает список заведений от координат.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        publicControllerFindAll(options?: AxiosRequestConfig): AxiosPromise<Array<BuildingsArrayInner>> {
            return localVarFp.publicControllerFindAll(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * PublicBuildingsApi - object-oriented interface
 * @export
 * @class PublicBuildingsApi
 * @extends {BaseAPI}
 */
export class PublicBuildingsApi extends BaseAPI {
    /**
     * 
     * @summary Возвращает список заведений от координат.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PublicBuildingsApi
     */
    public publicControllerFindAll(options?: AxiosRequestConfig) {
        return PublicBuildingsApiFp(this.configuration).publicControllerFindAll(options).then((request) => request(this.axios, this.basePath));
    }
}
